- .eslintrc.js
- contracts/UFragmentsPolicy.sol
- contracts/mocks/Mock.sol
- contracts/mocks/MockOracle.sol
- contracts/mocks/MockUFragments.sol
- test/unit/UFragmentsPolicy.js
- The policy now has no notion of volume.
- Using a cpi Oracle to compute the new `targetRate` on every rebase.
> Calculating a new target rate with every rebase using data from CPI Oracle

- contracts/UFragmentsPolicy.sol
This is going to save all the block calls since we would be able to use the timestamp from here instead of calling all the blocks individually and getting the timestamp from the block.
> add rebase timestamp to logs

- contracts/UFragmentsPolicy.sol
Fixed storage ordering issue with newly added  `baseCpi` variable
> updated variable ordering

- truffle.js
Disabling based on Trail of bits recommendation
"In light of the compiler audit released last fall as well as some recent high-severity bugs related to optimization issues, we currently caution against compiling with optimizations enabled unless the risk of potential latent optimizer bugs is carefully weighed against the gas savings optimizations would provide."
> Disabling compiler optimizations 

- contracts/UFragments.sol
- contracts/UFragmentsPolicy.sol
- test/unit/UFragments.js
- truffle.js
TOB feedback:
```
1) I think it would be a good idea to add an event in `UFragments.setMonetaryPolicy` so an event is emitted when the `monetaryPolicy` address is updated, so as to be consistent with other event triggers in the contracts.
2) There's also some variable shadowing happening in a few functions. Consider prefixing the function parameter names with an underscore in these cases for clarity. The relevant functions are `UFragmentsPolicy.initialize`, `UFragments.initialize` and `UFragments.allowance`. In each case it's the `owner` parameter shadowing so I'd suggest changing it to `_owner`.
3) I noticed there's a PR ready to be merged in `market-oracle` to enable compiler optimizations (and a similar one was merged earlier this month in `uFragments`). In light of the compiler audit …
```
> TOB recommendations

- contracts/UFragmentsPolicy.sol
- test/unit/UFragmentsPolicy.js
This was the previous behavior before https://github.com/ampleforth/uFragments/pull/109
> If oracle data is invalid apply 0 supply change instead of reverting transaction.

- contracts/UFragmentsPolicy.sol
- test/unit/UFragmentsPolicy.js
- util/blockchain_caller.js
Reverts ampleforth/uFragments#130
> Implemented rebase time window

- contracts/UFragmentsPolicy.sol
- test/unit/UFragmentsPolicy.js
- Set lastRebaseTimestampSec to the offset time instead of the beginning of the start of minRebaseTimeIntervalSec Cyclic interval
- Logging block time instead of snapped lastRebaseTimestampSec time during rebase
> Set lastRebaseTimestampSec to the offset time instead of the beginning of the start of minRebaseTimeIntervalSec cyclic interval

- contracts/UFragmentsPolicy.sol
- contracts/mocks/RebaseCallerContract.sol
- test/unit/UFragmentsPolicy.js
Protection from flash loans combined with rebase calls.
This change introduces tx.origin, but only to compare against msg.sender.
It does not use tx.origin for authentication.
> Disallow rebase calls from contracts

- contracts/Orchestrator.sol
- contracts/UFragmentsPolicy.sol
- test/unit/Orchestrator.js
Exhibit 1-
Remove Orchestrator address initialization in the policy.
Exhibit 2-
Reorder Transaction struct elements to pack values and save storage.
Exhibit 3-
No action. I'm ok with leaving the index in the `TransactionFailed` event, since risk is minimal and it aids potential debugging.
Exhibit 4-
No action needed.
Exhibit 5-
Removed unnecessary `delete` call.
Exhibit 6-
Removed `transferValueWei` parameter in external_call.
Exhibit 7-
Remove `dataLength` parameter in external_call. Load directly from array's storage.
Exhibit 8-
No action. It doesn't save gas, and I think it's more legible as is.
Exhibit 9-
Renamed `transactionsLength` to `transactionsSize` to follow market-oracle repo's convention.
Exhibit 10-
No action needed, since we mitigated Exhibit 2.
> Certik Audit Recommendations

- contracts/UFragments.sol
- test/unit/UFragments.ts
Adding public view 2 methods to the AMPL ERC-20, similar to [AAVE's aToken](https://docs.aave.com/developers/the-core-protocol/atokens) to expose the internal user balance and total supply.
* `scaledBalanceOf` : internal gon balance
* `scaledTotalSupply` : total number of gons
Fixes: https://github.com/ampleforth/uFragments/issues/179
> Elastic token standard: Interface update

- contracts/UFragments.sol
- contracts/UFragmentsPolicy.sol
> Updated function access modifiers 

- contracts/UFragmentsPolicy.sol
- test/unit/UFragmentsPolicy.ts
Added a getter on the Policy contract which returns the `globalAmpleforthEpoch` and `globalAMPLSupply`. The MonetaryPolicy (on the base chain) and the XCAmpleController on the satellite chains will implement this method.
When rebase is propagated between chains, its these 2 values which are transmitted. The method allows consumers to read both values atomically.  
fixes #188
> Add getGlobalAmpleforthEpochAndAMPLSupply

- contracts/UFragmentsPolicy.sol
- contracts/interfaces/IAMPL.sol
- contracts/interfaces/IAmpleforth.sol
- contracts/interfaces/IOrchestrator.sol
- test/unit/UFragmentsPolicy.ts
* Checked in standard public interface definition for, AMPL token, Ampleforth monetary policy and Orchestrator.
> Public Contract interfaces

- truffle.js
Adding truffle config file back as its used by out internal deployment script, and not having this file breaks our current setup.
Can remove once we move completely to hardhat
> Adding truffle config back

- contracts/Orchestrator.sol
- contracts/UFragments.sol
- contracts/UFragmentsPolicy.sol
- contracts/_external/ERC20Detailed.sol
- contracts/_external/IERC20.sol
- contracts/_external/Initializable.sol
- contracts/_external/Ownable.sol
- contracts/_external/SafeMath.sol
- contracts/lib/SafeMathInt.sol
- contracts/lib/UInt256Lib.sol
- contracts/mocks/ConstructorRebaseCallerContract.sol
- contracts/mocks/Mock.sol
- contracts/mocks/MockDownstream.sol
- contracts/mocks/MockOracle.sol
- contracts/mocks/MockUFragments.sol
- contracts/mocks/MockUFragmentsPolicy.sol
- contracts/mocks/RebaseCallerContract.sol
- contracts/mocks/SafeMathIntMock.sol
- contracts/mocks/UInt256LibMock.sol
- hardhat.config.ts
- package.json
- truffle.js
- yarn.lock
The AMPL ERC-20 (0.4.24) is currently dependent on Openzeppelin's `openzeppelin-eth` (v2.0.2) which has now been rebranded and upgraded to [openzeppelin-contracts-upgradeable](http://github.com/openZeppelin/openzeppelin-contracts-upgradeable/). The current version of openzeppelin contracts (v3.3.0) run on a more recent solidity version (0.6.12) but have modified the storage layout. 
To get around this (safest & dirty solution): 
* [Copied all external dependency contracts locally](https://github.com/ampleforth/uFragments/pull/195/commits/0598c766151322d7145b69dc9a0dfb6458a1f355) to `contracts/_external`
* [Bumped up the solidity compiler version in dependency](https://github.com/ampleforth/uFragments/pull/195/commits/2f32adba45aead6983b62d0b965b20e164540614) for the `_external` contracts …
> Upgrading token compiler version

- contracts/UFragments.sol
Replacing if statement with ternary operator in the decrease allowance function
> Replacing if statement with ternary operator

- contracts/Orchestrator.sol
- contracts/UFragments.sol
- contracts/UFragmentsPolicy.sol
- contracts/_external/ERC20Detailed.sol
- contracts/_external/IERC20.sol
- contracts/_external/Initializable.sol
- contracts/_external/Ownable.sol
- contracts/_external/SafeMath.sol
- contracts/lib/SafeMathInt.sol
- contracts/lib/UInt256Lib.sol
- contracts/mocks/ConstructorRebaseCallerContract.sol
- contracts/mocks/Mock.sol
- contracts/mocks/MockDownstream.sol
- contracts/mocks/MockOracle.sol
- contracts/mocks/MockUFragments.sol
- contracts/mocks/MockUFragmentsPolicy.sol
- contracts/mocks/RebaseCallerContract.sol
- contracts/mocks/SafeMathIntMock.sol
- contracts/mocks/UInt256LibMock.sol
- hardhat.config.ts
- truffle.js
Using solidity 0.7.x with optimizer and runs: 200
> Bumping up solidity to version 0.7.x

- contracts/UFragments.sol
This reverts commit b150071aba087d4cebfcfc68bd52043b1f95a214.
Rolling back some of the gas optimization changes as the new version of the compiler/optimizer handles all of them.
<pre>
·--------------------------------------------------|---------------------------|-------------|----------------------------·
|               Solc version: 0.7.6                ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 9500000 gas  │
···················································|···························|·············|·····························
|  Methods                                                                                                                │
·····················|·····························|·············|·············|·············|··············|··········· …
> Revert "gas optimization"

- contracts/Orchestrator.sol
Based on one of the help wanted issues [here](https://github.com/ampleforth/uFragments/issues/192), I updated the inline documentation to reflect the [patched change](https://github.com/ampleforth/uFragments/pull/153/). 
Currently if any of the transactions failed, the rebase function will ignore the failed transaction and continue with other transactions. However with the added revert call, the Orchestrator will revert the state changes and return a `Transaction failed` message.
@nithinkrishna
> Update inline documentation to document Orchestrator's revert

- contracts/UFragmentsPolicy.sol
Making MAX_SUPPLY variable private (as it was before)
https://github.com/ampleforth/uFragments/pull/193/files/212d341f03cd16c4ec50685c788e1dd807eeeded#diff-e22e448df35c045d975f17bf0a3b10a338128bf0147d6a92cc70d20de6576a49L83
> Fixed variable visibility

- contracts/Orchestrator.sol
Replacing custom externalCall function with the native solidity .call. With older versions of solidity (0.4.24) inline assembly is used to make external function calls. Now solidity supports [external function calls](https://docs.soliditylang.org/en/v0.6.1/control-structures.html#external-function-calls). Removing the externalCall function because it is not being used in the repo. Let me know if I should keep the externalCall function.
Based on the documentation, .call returns a boolean and bytes of memory.
`<address>.call(bytes memory) returns (bool, bytes memory)`
@nithinkrishna
> Replace custom external call with native solidity .call

- contracts/UFragmentsPolicy.sol
- contracts/interfaces/IAmpleforth.sol
- package.json
- test/unit/UFragmentsPolicy.ts
- yarn.lock
Added cpi and exchange rate getters
> Policy interface update

- contracts/UFragmentsPolicy.sol
- scripts/deploy.ts
- test/unit/UFragmentsPolicy.ts
We rebase with zero supply change when oracle inputs are invalid at the time of rebase
> Updated invalid oracle input handling

- contracts/UFragmentsPolicy.sol
- test/unit/UFragmentsPolicy.ts
Lower:-0.077
Upper: 0.05
Growth: 45
Deviation threshold 2.5%
> Update rebase curve parameters and deviation threshold

- contracts/MedianOracle.sol
- test/unit/MedianOracle.ts
Remove emit ReportTimestampOutOfRange so getData is read only
> Remove emit ReportTimestampOutOfRange so getData is read only
